// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-vkM-y5BI3hdLtgw_FWHPYWxrtjcG3V8',
    appId: '1:50945720064:web:48c3a1a486cdaa6cba3de5',
    messagingSenderId: '50945720064',
    projectId: 'sunday-suspense-14243',
    authDomain: 'sunday-suspense-14243.firebaseapp.com',
    storageBucket: 'sunday-suspense-14243.appspot.com',
    measurementId: 'G-CQDTDTPE5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnCIzi6qKv1LJKmKhqR1GLu6fVqYsvVwg',
    appId: '1:50945720064:android:ca46877ec54f647cba3de5',
    messagingSenderId: '50945720064',
    projectId: 'sunday-suspense-14243',
    storageBucket: 'sunday-suspense-14243.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGsEz7Ab__YfMU_ejLtsSww7JP4nI8Qig',
    appId: '1:50945720064:ios:f5424ba3bfce633aba3de5',
    messagingSenderId: '50945720064',
    projectId: 'sunday-suspense-14243',
    storageBucket: 'sunday-suspense-14243.appspot.com',
    iosClientId: '50945720064-1a40ats3fthtkvi1p6in3ih89aj5dnkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sundaySuspense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGsEz7Ab__YfMU_ejLtsSww7JP4nI8Qig',
    appId: '1:50945720064:ios:f5424ba3bfce633aba3de5',
    messagingSenderId: '50945720064',
    projectId: 'sunday-suspense-14243',
    storageBucket: 'sunday-suspense-14243.appspot.com',
    iosClientId: '50945720064-1a40ats3fthtkvi1p6in3ih89aj5dnkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sundaySuspense',
  );
}
